name: CI
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - "docs/**"
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - "docs/**"
      - '.gitignore'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - run: go build -o build ./cmd/